version: "3.9"
name: twenty

services:
  change-vol-ownership:
    image: ubuntu
    user: root
    volumes:
      - server-local-data:/tmp/server-local-data
      - docker-data:/tmp/docker-data
    command: >
      bash -c "
      chown -R 1000:1000 /tmp/server-local-data
      && chown -R 1000:1000 /tmp/docker-data"

  server:
    image: twentycrm/twenty:latest
    volumes:
      - server-local-data:/app/packages/twenty-server/${STORAGE_LOCAL_PATH:-.local-storage}
      - docker-data:/app/docker-data
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      PG_DATABASE_URL: postgres://twenty:twenty@db:5432/default
      SERVER_URL: http://localhost:3000
      FRONT_BASE_URL: ${FRONT_BASE_URL:-$SERVER_URL}
      MESSAGE_QUEUE_TYPE: pg-boss

      ENABLE_DB_MIGRATIONS: "true"

      SIGN_IN_PREFILLED: ${SIGN_IN_PREFILLED}
      STORAGE_TYPE: ${STORAGE_TYPE}
      STORAGE_S3_REGION: ${STORAGE_S3_REGION}
      STORAGE_S3_NAME: ${STORAGE_S3_NAME}
      STORAGE_S3_ENDPOINT: ${STORAGE_S3_ENDPOINT}
      ACCESS_TOKEN_SECRET: hK2n95N+98TODkzQaPa7KywibXKr1sBsyBudq61J1gI=
      LOGIN_TOKEN_SECRET: hK2n95N+98TODkzQaPa7KywibXKr1sBsyBudq61J1gI=
      REFRESH_TOKEN_SECRET: hK2n95N+98TODkzQaPa7KywibXKr1sBsyBudq61J1gI=
      FILE_TOKEN_SECRET: hK2n95N+98TODkzQaPa7KywibXKr1sBsyBudq61J1gI=
    depends_on:
      change-vol-ownership:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:3000/healthz
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always

  worker:
    image: twentycrm/twenty:latest
    command: ["yarn", "worker:prod"]
    environment:
      PG_DATABASE_URL: postgres://twenty:twenty@db:5432/default
      SERVER_URL: http://localhost:3000
      FRONT_BASE_URL: ${FRONT_BASE_URL:-$SERVER_URL}
      MESSAGE_QUEUE_TYPE: pg_boss

      ENABLE_DB_MIGRATIONS: "false" # it already runs on the server

      STORAGE_TYPE: ${STORAGE_TYPE}
      STORAGE_S3_REGION: ${STORAGE_S3_REGION}
      STORAGE_S3_NAME: ${STORAGE_S3_NAME}
      STORAGE_S3_ENDPOINT: ${STORAGE_S3_ENDPOINT}
      ACCESS_TOKEN_SECRET: hK2n95N+98TODkzQaPa7KywibXKr1sBsyBudq61J1gI=
      LOGIN_TOKEN_SECRET: hK2n95N+98TODkzQaPa7KywibXKr1sBsyBudq61J1gI=
      REFRESH_TOKEN_SECRET: hK2n95N+98TODkzQaPa7KywibXKr1sBsyBudq61J1gI=
      FILE_TOKEN_SECRET: hK2n95N+98TODkzQaPa7KywibXKr1sBsyBudq61J1gI=
    depends_on:
      db:
        condition: service_healthy
      server:
        condition: service_healthy
    restart: always

  db:
    image: twentycrm/twenty-postgres:latest
    volumes:
      - db-data:/bitnami/postgresql
    environment:
      POSTGRES_PASSWORD: replace_me_with_a_strong_password
    healthcheck:
      test: pg_isready -U twenty -d default
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always

volumes:
  docker-data:
  db-data:
  server-local-data:
